name: Scrape Table Sums with Playwright

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Scraper (23f3000880@ds.study.iitm.ac.in)
      run: node scrape_sum.js
